events {
    worker_connections 1024;
}

http {
    server_tokens off;
    
    server {
        listen 80;
        server_name jugglegames.com;

        location ~ /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
    }

    server {
        listen 80;
        server_name cloud.jugglegames.com;

        location ~ /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
    }
}