spring.datasource.url=jdbc:postgresql://${env.DOMAIN}:5432/${env.POSTGRES_DATABASE}
spring.datasource.username=test
spring.datasource.password=${env.POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver